
server:
  port: 8888

spring:
  application:
    name: service-fastdfs


#fastdfs配置
fdfs:
  so-timeout: 1500
  connect-timeout: 600
  pool:
    jmx-enabled: false
  thumb-image:  #缩略图生成
    width: 150
    height: 150
  tracker-list: 192.168.72.138:22122

#限制文件上传大小
multipart:
  enabled: true
  max-file-size: 50mb
  max-request-size: 50mb
